# Week-8: Reading Different File Formats using Pandas

Reading tab-delimited text, CSV, Excel and JSON files into DataFrames.

## a. Read Text Files

The text file is **tab-separated** and has no header row, so we pass the separator and column names explicitly.

In [5]:
import pandas as pd

txt_path = "datasets/student.txt"

students_txt = pd.read_csv(txt_path, sep="\t", names=["RollNo", "Name", "Marks"])
students_txt

   RollNo   Name  Marks
0     101  Aarav     88
1     102   Diya     92
2     103  Rohan     75
3     104  Meera     81

## b. Read CSV Files

A standard CSV already has a header row, so `read_csv` handles it directly.

In [6]:
csv_path = "datasets/student.csv"

students_csv = pd.read_csv(csv_path)
students_csv

   RollNo   Name  Marks
0     101  Aarav     88
1     102   Diya     92
2     103  Rohan     75
3     104  Meera     81

## c. Read Excel Files

Excel workbooks need the `openpyxl` engine; we load the first sheet.

In [7]:
xlsx_path = "datasets/student.xlsx"

students_xlsx = pd.read_excel(xlsx_path, sheet_name=0)
students_xlsx

   RollNo   Name  Marks
0     101  Aarav     88
1     102   Diya     92
2     103  Rohan     75
3     104  Meera     81

## d. Read JSON Files

The JSON file holds an array of record objects, which `read_json` turns into rows and columns.

In [8]:
json_path = "datasets/student.json"

students_json = pd.read_json(json_path, orient="records")
students_json

   RollNo   Name  Marks
0     101  Aarav     88
1     102   Diya     92
2     103  Rohan     75
3     104  Meera     81